blank_issues_enabled: false
contact_links:
  - name: NISER InfoBase Discussions
    url: https://github.com/JeS24/niser-info-base/discussions
    about: Please ask and answer questions about NISER InfoBase here.
